module.exports = [
{
    name: "Sougahoagdee Falls",
    state: "Alabama",
    city: "Houston,",
    description: "Huge rocks formation, lots of roots & rocks on the trail. The waterfall is at the end of the trail. Beware of leeches in the water & snakes along the way.",
    length: 4.0,
    elevationGain: 436,
    difficulty: "Easy",
    imageArray: "",
    hiked: false
},
{
    name: "Little River Canyon",
    state: "Alabama",
    city: "Fort Payne,",
    description: "Heavy rock areas where good balance is needed. Great access to water & swimming. Handicap access to an overlook.",
    length: 1.4,
    elevationGain: 190,
    difficulty: "Easy",
    imageArray: "",
    hiked: false
},
{
    name: "Cave Creek Trail from Cheaha Trailhead",
    state: "Alabama",
    city: "Lineville,",
    description: "Cave Creek has markings at trail junctions only. One very shallow water crossing. Some fallen trees to easily navigate around. The extra half mile to McDill Pointe is very worth the views.",
    length: 6.9,
    elevationGain: 1131,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Harding Icefield Trail",
    state: "Alaska",
    city: "Seward,",
    description: "Takes an average of 6 hours 29 min. Dogs are not allowed on this trail. Best times to visit: May - October. Pack layers, gets colder at the top.",
    length: 9.2,
    elevationGain: 3641,
    difficulty: "Hard",
    imageArray: "",
    hiked: false
},
{
    name: "Portage Pass Trail",
    state: "Alaska",
    city: "Whittier,",
    description: "Stunning views of Portage Glacier & Lake. The traile is very rocky and a bit steep. Wear good shoes ground is usually wet.",
    length: 4.2,
    elevationGain: 1433,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Horseshoe Lake Trail",
    state: "Alaska",
    city: "Denali National Park,",
    description: "Fee to enter. Kids under 15 get in free. Stairs and hills, gets flat once you reach the lake. Make sure to look for the beaver dam.",
    length: 2.1,
    elevationGain: 393,
    difficulty: "Easy",
    imageArray: "",
    hiked: false
},
{
    name: "Fossil Creek Falls",
    state: "Arizona",
    city: "Pine,",
    description: "Travel in a vehical suited for unpaved roads. A 1/4 mile walk from parking area to the waterfall trail then another mile to the waterfall. Enjoy a 25ft foot rock ledge that many people have jumped off of. Multiple swimming areas available. ",
    length: 2.42,
    elevationGain: 328,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Beaver Falls",
    state: "Arizona",
    city: "Supai,",
    description: "Enjoy incredible cascading pools over limestone terraces. Swim in the turquoise pools of Havasu Creek. It is recommended to start in the morning.",
    length: 5.2,
    elevationGain: 1200,
    difficulty: "Hard",
    imageArray: "",
    hiked: false
},
{
    name: "Apache Falls",
    state: "Arizona",
    city: "Whiteriver,",
    description: "A $15 permit is required. The walk to the falls takes no more than 10 minutes. You will definitely hear the falls before you see them. The parking lot overlooks the rushing river and high canyon mountains. The rock formations surrounding the falls act as steps and lounge space; perfect for relaxing and enjoying yourself with a beautiful view.",
    length: 1,
    elevationGain: 100,
    difficulty: "Easy",
    imageArray: "",
    hiked: false
},
{
    name: "Whitaker Point Trail (Hawksbill Crag)",
    state: "Arkansas",
    city: "Pettigrew,",
    description: "Situated deep into the Ozark National Forest, the Hawksbill Crag is an Arkansas treasure. Thousands of hikers every year traverse the Whitaker Point Trail up to the beautiful rocky viewpoint.",
    length: 2.9,
    elevationGain: 413,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "White Rock Rim Trail",
    state: "Arkansas",
    city: "Winslow,",
    description: "Generally considered an easy route, it takes an average of 45 min to complete. This is a popular trail for birding, camping, and hiking, but you can still enjoy some solitude during quieter times of day.",
    length: 2.1,
    elevationGain: 147,
    difficulty: "Easy",
    imageArray: "",
    hiked: false
},
{
    name: "Lost Valley Trail",
    state: "Arkansas",
    city: "Ponca,",
    description: "You'll need to leave pups at home — dogs aren't allowed on this trail. The Lost Valley Trail leads along Clark Creek, past several natural bridges, to the end destination of Eden Falls and Cobb Cave. The hiking trail is relatively short, giving you plenty of time for exploring the caves and rock formations.",
    length: 2.3,
    elevationGain: 252,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Emerald Bay via Lighthouse & Rubicon Trail",
    state: "California",
    city: "South Lake Tahoe,",
    description: "The Rubicon Trail along the southwest shore of South Lake Tahoe is a gem! Not to be confused with the famous OHV route of the same name that is located nearby, this hiking trail travels between both Emerald Bay State Park and D.L. Bliss State Park in the Sierra Nevada Mountains.",
    length: 16.4,
    elevationGain: 2306,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Vernal & Nevada Falls via Mist Trail",
    state: "California",
    city: "Yosemite Valley,",
    description: "You'll need to leave pups at home — dogs aren't allowed on this trail. Hike to two breathtaking waterfalls along some of Yosemite Valley's most popular hiking trails. If you only have time for one hike while in Yosemite look no further - the Mist Trail is the hike for you. It is no wonder why this trail is one of the most traveled in Yosemite National Park. You will hike so close to these two massive waterfalls that you may get wet from the trail. The best time to hike this trail is in Spring or early Summer, while the snow runoff is high and the falls are full of water.",
    length: 6,
    elevationGain: 2162,
    difficulty: "Hard",
    imageArray: "",
    hiked: false
},
{
    name: "Upper Yosemite Falls Trail",
    state: "California",
    city: "Yosemite Valley,",
    description: "Yosemite National Park charges a fee to enter. Enjoy the incredible views of looking down from the top of Yosemite Falls, the tallest waterfall in the continental US. Yosemite Falls, dropping 2,425 feet to the bottom of the valley from the top, is one of the most visited places in Yosemite National Park.",
    length: 7.6,
    elevationGain: 3218,
    difficulty: "Hard",
    imageArray: "",
    hiked: false
},
{
    name: "Land End Trail",
    state: "California",
    city: "San Francisco,",
    description: "Lands End Trail is a favorite among both locals and visitors alike! This trail explores the historic Sutro Baths and offers great views of the Golden Gate Bridge and the Pacific Ocean. A must see for any visitor to San Francisco.",
    length: 3.4,
    elevationGain: 538,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Panorama Loop",
    state: "California",
    city: "Yucca Valley,",
    description: "Joshua Tree National Park charges a fee to enter. Panorama Loop Trail offers some of the most interesting higher elevation flora and some of the most spectacular views within all of Joshua Tree National Park. You'll hike up a sandy wash before climbing up a ridge and exploring the Little San Bernadino Mountains. ",
    length: 6.6,
    elevationGain: 1194,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Chasm Lake",
    state: "Colorado",
    city: "Estes Park,",
    description: "Rocky Mountain National Park charges a fee to enter. Chasm Lake is a classic, must-do Colorado hike. You’ll get incredible views while traversing the subalpine forest up to the alpine tundra. The lake sits below the spectacular Long’s Peak, the highest in the park",
    length: 8.8,
    elevationGain: 2542,
    difficulty: "Hard",
    imageArray: "",
    hiked: false
},
{
    name: "Animas Mountain Trail",
    state: "Colorado",
    city: "Durango,",
    description: "This is a very popular area for hiking, mountain biking, and rock climbing, so you'll likely encounter other people while exploring. The best times to visit this trail are March through October. Dogs are welcome and may be off-leash in some areas.",
    length: 6,
    elevationGain: 1519,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Emerald Lake Trail",
    state: "Colorado",
    city: "Estes Park,",
    description: " Rocky Mountain National Park charges a fee to enter. This scenic hiking trail through the Tyndall Gorge to Emerald Lake is an extremely popular route in Rocky Mountain National Park. Starting from the Bear Lake Trailhead, hikers will walk through pine forests, past pristine alpine lakes including Nymph Lake and Dream Lakes, and be treated to beautiful vistas of rocky peaks.",
    length: 3.2,
    elevationGain: 698,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Hanging Lake Trail",
    state: "Colorado",
    city: "Glenwood Springs,",
    description: "A permit is required. Hanging Lake Trail is one of Colorado's most visited and beautiful short hikes. Perched high in the mountains, the trail takes you along Dead Horse Creek and through the rocky Glenwood Canyon. It is a national natural landmark in the White River National Forest near Glenwood Springs, Colorado that can be reached easily from Denver",
    length: 3.1,
    elevationGain: 1187,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Cascade Creek Trail to Mirror Lake & Crater Lake",
    state: "Colorado",
    city: "Tabernash,",
    description: "This is one of the most consistently scenic hikes in the area, with outstanding views of diverse Colorado landscapes around every turn. Starting from the Monarch Lake Trailhead, this is a well-maintained trail that is never too steep, so it's a fun hike from start to finish. Following Cascade Creek provides a number of great places to rest and enjoy the numerous waterfalls and pools right off the trail. There are aspen groves, and wildflowers, and the destination of Crater Lake with 360 degrees of stunning cliffs, glaciers, and a pristine alpine lake",
    length: 16,
    elevationGain: 2322,
    difficulty: "Hard",
    imageArray: "",
    hiked: false
},
{
    name: "Ice Lake Basin",
    state: "Colorado",
    city: "Silverton,",
    description: "This is a beautiful trail in the San Juan National Forest with awesome views all the way up. This loop can be very difficult if you aren’t used to the elevation gain, as there is plenty of climbing along this route. Throughout your journey through the Ice Lake Basin, you’ll pass waterfalls, meandering creeks, and one of the most beautifully colored lakes you will ever see! The stunning views and unique landscape on this trip make every bit of climbing worth the effort.",
    length: 8.3,
    elevationGain: 2877,
    difficulty: "Hard",
    imageArray: "",
    hiked: false
},
{
    name: "South Colony Lakes Trail",
    state: "Colorado",
    city: "Crestone,",
    description: "A high clearance vehicle is recommended to get to the trailhead. Beautiful hike! It's definitely worth it to go to the upper lake. The best times to visit this trail are March through October. Dogs are welcome and may be off-leash in some areas.",
    length: 8.9,
    elevationGain: 2286,
    difficulty: "Hard",
    imageArray: "",
    hiked: false
},
{
    name: "Fish Creek Falls Trail",
    state: "Colorado",
    city: "Steamboat Springs,",
    description: "$5 vehicle day use fee - cash or check. The best times to visit this trail are May through September. Dogs are welcome, but must be on a leash. Fish Creek Falls is a 283 foot waterfall located about 5 miles outside of Steamboat Springs. The route is used by hikers during the summer and is a beautiful trail to snowshoe in the winter. Along the way you'll pass by two beautiful waterfalls, Lower and Upper Fish Creek Falls. The lower falls are generally more impressive.",
    length: 4.7,
    elevationGain: 1450,
    difficulty: "Hard",
    imageArray: "",
    hiked: false
},
{
    name: "Saint Mary's Glacier",
    state: "Colorado",
    city: "Idaho Springs,",
    description: "Located a short distance from Idaho Springs, Colorado, this short hike to St. Mary’s Glacier offers spectacular views and the chance to visit a beautiful alpine lake and glacier. This is a great option for day trips year round, as the snow covered landscape during the winter makes for some amazing views at the top. The best times to visit this trail are April through October. Dogs are welcome, but must be on a leash.",
    length: 2.4,
    elevationGain: 1030,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Quandry Peak Trail",
    state: "Colorado",
    city: "Blue River,",
    description: "Parking at this trailhead is available by reservation only. The trail is open year-round and is beautiful to visit anytime. Dogs are welcome, but must be on a leash. The trail is rocky, but unlike many other 14ers, this one does not require any technical scrambling. Keep your eyes peeled for the mountain goats that are known to inhabit the area! Once at the summit, you’ll have beautiful views of the Gore and Sawatch Ranges.",
    length: 6.6,
    elevationGain: 3326,
    difficulty: "Hard",
    imageArray: "",
    hiked: false
},
{
    name: "Bear Mountain Trail",
    state: "Connecticut",
    city: "Taconic,",
    description: "The best times to visit this trail are March through November. Dogs are welcome and may be off-leash in some areas. The Bear Mountain Trail is one of the most popular trails in Mount Riga State Park. There are spectacular views from the top. Bear Mountain is the highest peak in Connecticut. The trail is steep and rocky in sections and can be icy and snow covered depending on the season. ",
    length: 6.1,
    elevationGain: 1683,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Ragged Moutain Blue & Red Blazed Loop",
    state: "Connecticut",
    city: "Berlin,",
    description: "This rugged trail features expansive vistas with breathtaking views of the Wassel Reservoir, as well as rocks to sit on to take in the views and beautiful fall colors. Come in the winter for snowshoeing. The blue and red loop is more rocky than the orange trail, but features rock formations, vernal pools, epic cliff face views, and a cool waterfall. ",
    length: 5.6,
    elevationGain: 843,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Chauncey Peak Trail",
    state: "Connecticut",
    city: "Meriden,",
    description: "I world recommend counter clockwise for non serous hikers. There is a very steep and rocky section right near trail head. With counter clockwise you climb, rather than descend, through most challenging section. The best times to visit this trail are April through October. Dogs are welcome and may be off-leash in some areas. ",
    length: 2.2,
    elevationGain: 351,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Zoar Trail",
    state: "Connecticut",
    city: "Stevenson,",
    description: "The best times to visit this trail are March through October. Dogs are welcome, but must be on a leash. Well marked, changing terrains, lots of flowers. ",
    length: 7,
    elevationGain: 1072,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Alapocas Woods Trail",
    state: "Delaware",
    city: "Rockland,",
    description: "The best times to visit this trail are February through November. Dogs are welcome, but must be on a leash. Great trails. some pretty steep hills. Lots of waterfalls",
    length: 1.8,
    elevationGain: 226,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Indian Springs Trail",
    state: "Delaware",
    city: "Wilmington,",
    description: " Brandywine Creek State Park charges an entrance fee. Beautiful forest hike up and down hills to Brandywine Creek then back up and through some very large tulip trees.  Look for the stone fences which mark the borders of the Du Pont family fields. The trail is well marked with yellow trail markers. The trail is open year-round and is beautiful to visit anytime. Dogs are welcome, but must be on a leash.",
    length: 2.3,
    elevationGain: 190,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Junction & Breakwater Trail",
    state: "Delaware",
    city: "Rehoboth Beach,",
    description: "This is a nice wide and well-maintained gravel trail. It is great for cycling, running, or walking. The trail is open year-round and is beautiful to visit anytime. Dogs are welcome, but must be on a leash.",
    length: 5.8,
    elevationGain: 98,
    difficulty: "Easy",
    imageArray: "",
    hiked: false
},
{
    name: "Robinson's Preserve Full Trail System",
    state: "Florida",
    city: "Cortez,",
    description: "This is a route that includes a combination of all of. the trails and overlooks in the preserve. There are partially paved trails with an area of challenging single track thru the mangroves. The paved section is about 2.5 miles long. The Preserve is also popular for paddle sports, biking, fishing, and bird watching. The best times to visit this trail are October through May. Dogs are welcome, but must be on a leash. ",
    length: 7.5,
    elevationGain: 49,
    difficulty: "Easy",
    imageArray: "",
    hiked: false
},
{
    name: "Econ River Wilderness Area Red Loop",
    state: "Florida",
    city: "Oviedo,",
    description: "This is a beautiful trail that is mostly shaded and leads to several different bodies of water. There are many opportunities to observe wildlife and local plants along the way. For those wishing to extend their hike, there are other trails to connect to in the area. This is a great place for the whole family to enjoy which is easily accessible. The trail is open year-round and is beautiful to visit anytime. Dogs are welcome, but must be on a leash. ",
    length: 2.6,
    elevationGain: 42,
    difficulty: "Easy",
    imageArray: "",
    hiked: false
},
{
    name: "Mount Yonah Trail",
    state: "Georgia",
    city: "Cleveland,",
    description: "Users have suggested that when using a map program, make sure to input 'Mt Yonah' not 'Yonah Mountain' to get to the trailhead.This climb is challenging but it is one of the best views once you reach the top of the mountain.  Afterward, you can enjoy a craft beer or visit the local winery. The best times to visit this trail are February through November. Dogs are welcome and may be off-leash in some areas. ",
    length: 4.5,
    elevationGain: 1466,
    difficulty: "Hard",
    imageArray: "",
    hiked: false
},
{
    name: "Raven Cliff Falls Trail",
    state: "Georgia",
    city: "Helen,",
    description: "There is a $5 fee to park at the trailhead. The incline on this beautiful trail is moderate until the end. The trail follows Dodd Creek over roots and rocks the whole way in, allowing for great views, and opportunity to cool down or for pets to get a quick drink. The trail is fun, with lots of different terrain to navigate which keeps it interesting. The Raven Cliff Falls area is amazing, and a great place to enjoy the water and watch Matthews Creek cascade down Raven Cliff.  The trail is open year-round and is beautiful to visit anytime. Dogs are welcome, but must be on a leash.",
    length: 5.8,
    elevationGain: 564,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Amicalola Falls via East Ridge Loop Trail",
    state: "Georgia",
    city: "Marble Hill,",
    description: "This is a track from the bottom of Amicacola Falls to the top. From there up to the AT approach trail and back. Fun loop for all. Well marked and the falls are beautiful! The trail is open year-round and is beautiful to visit anytime. Dogs are welcome, but must be on a leash.",
    length: 2,
    elevationGain: 784,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Stone Mountain Walk-up Trail",
    state: "Georgia",
    city: "Stone Mountain,",
    description: "The hike is entirely on smooth granite rock. Although there is a route defined, the 'trail' can be very wide, with stands of trees dotting the rock face. Stone Mountain Park charges a fee for parking. If you are entering on foot or bike there is no fee. The trail is open year-round and is beautiful to visit anytime. You'll need to leave pups at home — dogs aren't allowed on this trail.",
    length: 2.2,
    elevationGain: 567,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Iron Hill Trail",
    state: "Georgia",
    city: "Cartersville,",
    description: "Red Top Mountain State Park charges a fee to enter. This is a fully gravel trail that makes for a great short hike. If you are hiking from the campground entrance of the trail, it is closer to 5.5 miles round trip. The trail is open year-round and is beautiful to visit anytime. Dogs are welcome, but must be on a leash.",
    length: 3.4,
    elevationGain: 141,
    difficulty: "Easy",
    imageArray: "",
    hiked: false
},
{
    name: "Koko Crater Tramway to Kokohead Lookout",
    state: "Hawaii",
    city: "Honolulu, Oahu",
    description: "The 1,000+ step walking track consists of abandoned railroad ties that run along the crater's west side to the top of Koko Crater. The military used them previously during World War 2 as part of an incline tram to transport supplies to a lookout post at the summit. Halfway up, there is a 'bridge' portion without ground beneath ~50 rail steps, but there is bypassing trail if you're scared. The trail is open year-round and is beautiful to visit anytime. You'll need to leave pups at home — dogs aren't allowed on this trail.",
    length: 1.6,
    elevationGain: 885,
    difficulty: "Hard",
    imageArray: "",
    hiked: false
},
{
    name: "Waihe's Ridge Trail",
    state: "Hawaii",
    city: "Wailuku, Maui",
    description: "Hiking the Waihee ridgeline up in the west Maui mountains overlooking the Waihe’e Valley is dramatic and always scenic. There is a well-groomed trail that is suitable for trail runners and hikers alike. The elevation climbs by means of clean switch-backs and stairs spaced apart by spots of flat terrain. Good views are available if hiking on a clear day but be prepared for moderate sun exposure. The trail is open year-round and is beautiful to visit anytime. Dogs are welcome, but must be on a leash.",
    length: 4,
    elevationGain: 1670,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Kuliouou Ridge Trail",
    state: "Hawaii",
    city: "Honolulu, Oahu",
    description: "This trail rises almost 1,800 feet before peaking on the spine of the awe inspiring Kuli’ou’ou Ridge. At the top of the ridge you are rewarded with sweeping views of the dramatic landscape around you. The trail is steep and can be wet and slippery so best to be prepared for muddy conditions, as is common with many hikes on the island. The trail is open year-round and is beautiful to visit anytime. Dogs are welcome and may be off-leash in some areas.",
    length: 4.7,
    elevationGain: 1650,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Makapu's Point Lighthouse Trail",
    state: "Hawaii",
    city: "Waimānalo, Oahu",
    description: "Great short uphill paved trail along sea cliffs to observation deck and lighthouse with fantastic views. Whole thing is paved, there's no shade so bring lots of water and go as soon as they open to beat the heat. Lots of lookouts for whales, you can climb down a path and get right next to the lighthouse. The trail is open year-round and is beautiful to visit anytime. Dogs are welcome, but must be on a leash.",
    length: 2.5,
    elevationGain: 505,
    difficulty: "Easy",
    imageArray: "",
    hiked: false
},
{
    name: "Tubbs Hill",
    state: "Idaho",
    city: "Coeur d'Alene,",
    description: "This popular path loops around Tubbs Hill just south of Coeur d'Alene. You can walk from downtown, pass McEuen Park, and get right onto the trail! There's even a beach on the southwestern side of the loop. The best times to visit this trail are May through October. Dogs are welcome and may be off-leash in some areas.",
    length: 2,
    elevationGain: 291,
    difficulty: "Easy",
    imageArray: "",
    hiked: false
},
{
    name: "Redfish Lake Trail 902",
    state: "Idaho",
    city: "Stanley,",
    description: "Take plenty of water for this portion of the track as it's mostly uphill and places to fill up are scarce. Scenery is fantastic along the way. Takes an average of 6 h 23 min to complete.",
    length: 12.4,
    elevationGain: 2736,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Imogene Lake",
    state: "Idaho",
    city: "Stanley,",
    description: "Imogene Lake is a stunning high alpine lake with a complicated shoreline due to the geologic jointing in the underlying bedrock. Several islands dot the lake, the largest of which is connected by an isthmus to the north shore. The trail to Imogene hugs the eastern side of the lake/drainage before making the final climb through numerous switchbacks to the divide with the Yellow Belly drainage. The best times to visit this trail are June through October. Dogs are welcome, but must be on a leash.",
    length: 13.4,
    elevationGain: 1459,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Goldbug (Elk Bend) Hot Springs",
    state: "Idaho",
    city: "Salmon,",
    description: "This area is very popular so you will be sharing the springs with lots of other hikers, so bring a bathing suit. You can camp in the area, but you may want to camp in the flat part before the hot springs as the springs themselves are in a canyon with few flat spots. The trail is open year-round and is beautiful to visit anytime. Dogs are welcome, but must be on a leash.",
    length: 3.6,
    elevationGain: 895,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Scotchman Peak Trail",
    state: "Idaho",
    city: "Clark Fork,",
    description: "The woods are nice and you can see signs of mountain goats along the way. Watch out for hornets, as the trail is teeming with them. Once you get into the shale above the tree line, the landscape becomes much more dramatic and rugged with some fantastic views. Not too crowded either. The view from the peak is wonderful. The best times to visit this trail are March through October. Dogs are welcome, but must be on a leash.",
    length: 8.7,
    elevationGain: 3664,
    difficulty: "Hard",
    imageArray: "",
    hiked: false
},
{
    name: "Stevens Lakes Trail",
    state: "Idaho",
    city: "Mullan,",
    description: "This hike is diverse in landscape, including areas of traversing over rock slides. However, the fantastic views of the mountains, waterfalls, and lakes are worth the effort! The best times to visit this trail are June through October. Dogs are welcome, but must be on a leash.",
    length: 5.0,
    elevationGain: 1824,
    difficulty: "Hard",
    imageArray: "",
    hiked: false
},
{
    name: "Upper Palisades Lake Trail",
    state: "Idaho",
    city: "Irwin,",
    description: "Long day hike! Lake was worth it! Gorgeous Caribbean turquoise water! Unbelievable! The best times to visit this trail are June through October. Dogs are welcome, but must be on a leash.",
    length: 15.0,
    elevationGain: 1679,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Boulder Lake Loop Trail",
    state: "Idaho",
    city: "Lake Fork,",
    description: "Trail is in very good shape and easy to navigate. Louie Lake was very nice as was Boulder Lake. The downhill from Boulder Lake to Boulder Reservoir was rocky and steep so tracking poles are a good idea. The meadows and views between Louie Lake and Boulder Lake are incredible with all of the wildflowers. The best times to visit this trail are May through October. Dogs are welcome, but must be on a leash.",
    length: 6.9,
    elevationGain: 1633,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Waterfall Glen Trail",
    state: "Illinois",
    city: "Willowbrook,",
    description: "This stellar trail features a wide, gravel-paved path that passes small bodies of water and a waterfall. It is a long but easy trail. The best times to visit this trail are April through October. Dogs are welcome, but must be on a leash.",
    length: 9.3,
    elevationGain: 400,
    difficulty: "Easy",
    imageArray: "",
    hiked: false
},
{
    name: "Little Grand Canyon Trail",
    state: "Illinois",
    city: "Pomona,",
    description: "There are a couple of places where you have to climb down into the canyon through the creek bed. It can be slippery and difficult when the creek is flowing. Must have good footwear for this trail. Beautiful trail, but the technical aspects are why it is rated as difficult. The trail is open year-round and is beautiful to visit anytime. Dogs are welcome, but must be on a leash.",
    length: 3.4,
    elevationGain: 508,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Indian Point Trail",
    state: "Illinois",
    city: "Harrisburg,",
    description: "Indian Point trail works its way through pine forest transitioning to hardwood timber before reaching the crest of the hill overlooking the surrounding valley. From there you descend below the bluff looping back to the trailhead passing many large rock formations. The trail is open year-round and is beautiful to visit anytime. Dogs are welcome, but must be on a leash.",
    length: 1.7,
    elevationGain: 187,
    difficulty: "Easy",
    imageArray: "",
    hiked: false
},
{
    name: "Cowles Bog Trail",
    state: "Indiana",
    city: "Dune Acres,",
    description: "The Cowles Bog Trail highlights an area of such outstanding plant diversity that it was designated as a National Natural Landmark in 1965. This location, where Dr. Henry Cowles conducted much of his early work in plant ecology and succession in the early 1900s, remains an important focus for scientific study today. Explore several distinct habitats along this trail including ponds, marshes, swamps, black oak savannas and beaches. Indiana Dunes National Park charges a fee to enter. The trail is open year-round and is beautiful to visit anytime. Dogs are welcome, but must be on a leash.",
    length: 4.3,
    elevationGain: 216,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Three Lakes Trail",
    state: "Indiana",
    city: "Martinsville,",
    description: "Well marked forest loop. Some challenging hills so be prepared. Very little water on the trail so bring at least a couple of liters. The trail is open year-round and is beautiful to visit anytime. Dogs are welcome, but must be on a leash.",
    length: 10.6,
    elevationGain: 1177,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "West Beach - Dune Succession Trail",
    state: "Indiana",
    city: "Portage,",
    description: "This scenic, but strenuous, trail includes a climb up 250 stairs for a spectacular view of Lake Michigan and Chicago. Please support restoration effort in the fragile dunes and ponds by remaining on designated trails. Indiana Dunes National Park charges a fee to enter. The best times to visit this trail are April through October. Dogs are welcome, but must be on a leash. ",
    length: 1.1,
    elevationGain: 95,
    difficulty: "Easy",
    imageArray: "",
    hiked: false
},
{
    name: "Dozer Cut, Bunker Hill, & Badger Ridge Trail Loop",
    state: "Iowa",
    city: "Honey Creek,",
    description: "This loop combines the best of the trails at Hitchcock Nature Center for one of the most adventurous treks in the Omaha area! Located north of Omaha and across the Iowa border, this park really makes you feel as if you've gone off the grid. The trail is open year-round and is beautiful to visit anytime. Dogs are welcome, but must be on a leash.",
    length: 6.3,
    elevationGain: 1269,
    difficulty: "Hard",
    imageArray: "",
    hiked: false
},
{
    name: "Squire Shore, Weasel Run, Mushroom Forest Trail",
    state: "Iowa",
    city: "North Liberty,",
    description: " Easy to navigate. Pretty scenery, shaded trail, and benches along the way. The trail is open year-round and is beautiful to visit anytime. Dogs are welcome, but must be on a leash.",
    length: 5,
    elevationGain: 364,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Canyon Road & Table Rock Loop",
    state: "Iowa",
    city: "Boone,",
    description: "The trail is open year-round and is beautiful to visit anytime. Dogs are welcome, but must be on a leash.",
    length: 1.7,
    elevationGain: 429,
    difficulty: "Mderate",
    imageArray: "",
    hiked: false
},
{
    name: "Wyandotte County Lake Loop Trail",
    state: "Kansas",
    city: "Kansas City,",
    description: "This loop presents a healthy challenge for the weekend warrior. Along the trail you will encounter several different types of terrain. It is recommend equipping yourself with bug spray, hiking boots, and tall socks. The trail is open year-round and is beautiful to visit anytime. Dogs are welcome, but must be on a leash.",
    length: 10.4,
    elevationGain: 1322,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Indian Creek Trail",
    state: "Kansas",
    city: "Olathe,",
    description: "Besides a couple of signalized crosswalks, the bridges, tunnels, parks, creek and artwork hanging in some of the trees provided a nice scenery. The trail is open year-round and is beautiful to visit anytime. Dogs are welcome, but must be on a leash.",
    length: 22.5,
    elevationGain: 311,
    difficulty: "Easy",
    imageArray: "",
    hiked: false
},
{
    name: "Konza Prairie Nature Trail Loop",
    state: "Kansas",
    city: "Manhattan,",
    description: "The trail is lined with limestone pea gravel or follows a service road that is either bare dirt or limestone gravel. The best times to visit this trail are April through June. You'll need to leave pups at home — dogs aren't allowed on this trail.",
    length: 2.7,
    elevationGain: 265,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Double Arch, Courthouse Rock & Auxier Ridge Loop",
    state: "Kentucky",
    city: "Stanton,",
    description: "he double arch is gorgeous and well worth the hike there. Nice photo ops too. Just try to go during the week not on a weekend. There were too many other hikers there parked along the road and on the trails. The trail is open year-round and is beautiful to visit anytime. Dogs are welcome, but must be on a leash.",
    length: 6,
    elevationGain: 1036,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Copperas Falls",
    state: "Kentucky",
    city: "Pine Ridge,",
    description: "Beautiful hike! Only knock is the trail is not marked and you have to guess sometimes where to cross the creek but it added some fun. The trail is open year-round and is beautiful to visit anytime. Dogs are welcome, but must be on a leash.",
    length: 3.1,
    elevationGain: 167,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Sky Bridge Red River Gorge",
    state: "Kentucky",
    city: "Pine Ridge,",
    description: "As scenic a view as you can find out into the Red River Gorge. This is an amazing natural bridge. There are a decent amount of stairs on this trek. The best times to visit this trail are January through October. Dogs are welcome, but must be on a leash.",
    length: 0.8,
    elevationGain: 216,
    difficulty: "Easy",
    imageArray: "",
    hiked: false
},
{
    name: "Bogue Chitto State Park Gorge Run Trail",
    state: "Louisiana",
    city: "Franklinton,",
    description: "Nice trail, very well-marked and well-maintained. Not very difficult, but you should definitely bring water along with you (there are refill/bathroom stations along the path). There’s a tree down across the trail around 1.8mi or so in (if going clockwise), but not difficult to step over. Multiple points in the trail where it winds out along the bank of the river, makes for some good views. The trail is open year-round and is beautiful to visit anytime. Dogs are welcome, but must be on a leash.",
    length: 5.7,
    elevationGain: 239,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Driskill Mountain Trail",
    state: "Louisiana",
    city: "Bienville,",
    description: "This is an easy hike to the Louisiana state highpoint. The summit and trail are well marked and maintained. There is an alternate route over False Mountain that is also clearly marked. For such a low highpoint, this is quite a nice area. The trail is open year-round and is beautiful to visit anytime. Dogs are welcome and may be off-leash in some areas.",
    length: 1.8,
    elevationGain: 167,
    difficulty: "Easy",
    imageArray: "",
    hiked: false
},
{
    name: "Lake Chicot Loop Trail",
    state: "Louisiana",
    city: "Ville Platte,",
    description: "Great trails with a lot of scenery. Horse flies can be a pain. The trails a mostly shaded and recommend extra socks and plenty of water. The best times to visit this trail are October through June. Dogs are welcome, but must be on a leash.",
    length: 17.3,
    elevationGain: 744,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "The Beehive Loop Trail",
    state: "Maine",
    city: "Bar Harbor,",
    description: "The Beehive Trail Loop is a must-do hike for all visitors to Acadia National Park. This popular loop offers incredible views, with some challenging rung and ladder sections. This loop starts at the Sand Beach Parking Lot, traverses over the Beehive, reaches the Bowl Pond, and then loops back on the Bowl Trail. Acadia National Park charges a fee to enter. The best times to visit this trail are May through October. You'll need to leave pups at home — dogs aren't allowed on this trail.",
    length: 1.5,
    elevationGain: 508,
    difficulty: "Hard",
    imageArray: "",
    hiked: false
},
{
    name: "Jordan Pond Path",
    state: "Maine",
    city: "Mount Desert,",
    description: "he backdrop of the pond and bubbles are beautiful as you meander through the woods along the pond. The boardwalks are unique, and outside of a couple of muddy spots, a trail that is very enjoyable and easy. Acadia National Park charges a fee to enter. The best times to visit this trail are April through October. Dogs are welcome, but must be on a leash.",
    length: 3.1,
    elevationGain: 42,
    difficulty: "Easy",
    imageArray: "",
    hiked: false
},
{
    name: "Precipice Loop",
    state: "Maine",
    city: "Bar Harbor,",
    description: "The view from the top of the hike is definitely great and worth it. I will give my feedback for not the views but how to get there it is not a hike it is more like a bouldering activity where you have to keep climbing on small medium to large boulders and this has been covered well by others. Acadia National Park charges a fee to enter The best times to visit this trail are May through October. You'll need to leave pups at home — dogs aren't allowed on this trail.", 
    length: 2.1,
    elevationGain: 1053,
    difficulty: "Hard",
    imageArray: "",
    hiked: false
},
{
    name: "Gret Head Trail (Full Loop",
    state: "Maine",
    city: "Seal Harbor,",
    description: "The Great Head Trail features rocky outcroppings, sandy beach access, and ocean views over a short distance. Along the way hikers will see the remains of an old stone tower which formerly housed an observatory and tea room. The best times to visit this trail are April through October. Dogs are welcome, but must be on a leash.",
    length: 1.8,
    elevationGain: 265,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Sugarloaf Mountain & Northern Peaks Trail",
    state: "Maryland",
    city: "Dickerson,",
    description: "Users recommend arriving early to avoid parking area issues, along with helping to avoid crowds at the peaks but otherwise not too many are normally on the trails themselves. Most of the trail is rocky or uneven with tree roots, so wearing proper footwear is advised.  The trail is open year-round and is beautiful to visit anytime. Dogs are welcome, but must be on a leash.",
    length: 7.4,
    elevationGain: 1519,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Weverton Cliffs",
    state: "Maryland",
    city: "Knoxville,",
    description: "The trail starts by going up a bunch of stone steps. This trail is all switchbacks and sometimes a little steep. Make sure to bring water and a little snack to enjoy at the top while you sit back and enjoy the view. Going back is easier as it’s pretty much all down hill. Just be sure to wear some good hiking boots or a shoe with good traction as there is a lot of rocks on the trail. Best to go on a weekday to avoid crowds. The trail is open year-round and is beautiful to visit anytime. Dogs are welcome, but must be on a leash.",
    length: 1.9,
    elevationGain: 567,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Swallow Falls Canyon Trail",
    state: "Maryland",
    city: "Oakland,",
    description: "$5 for out of state visitors. The trail is open year-round and is beautiful to visit anytime. You'll need to leave pups at home — dogs aren't allowed on this trail.",
    length: 1.1,
    elevationGain: 137,
    difficulty: "Easy",
    imageArray: "",
    hiked: false
},
{
    name: "Catoctin Mountain Extended Loop Trail",
    state: "Maryland",
    city: "Thurmont,",
    description: "Ranges from an easy walk to a challenging uphill hike, but the beautiful vistas make it well worth the effort. The park also has many interesting geological formations and wildlife. The trail is very rocky in many areas. The best times to visit this trail are March through November. Dogs are welcome, but must be on a leash.",
    length: 9.9,
    elevationGain: 1738,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Great Blue Hill via Skyline Trail",
    state: "Massachusetts",
    city: "Milton,",
    description: "Great Blue Hill via Skyline Trail is a relatively short and moderate hike in the forests of the Blue Hills Reservation. The hiking trail offers great views of the downtown Boston skyline and Eliot Tower is a fantastic lookout point to see the entire Boston region. The best times to visit this trail are April through October. Dogs are welcome, but must be on a leash.",
    length: 3.0,
    elevationGain: 813,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Mount Greylock via Bellows Pipe Trail",
    state: "Massachusetts",
    city: "Adams,",
    description: "Mount Greylock via Bellows Pipe Trail starts from the Gould Road/Bellows South parking area. Mount Greylock is the highest point in Massachusetts at 3,491 feet and is located in Mount Greylock State Reservation. On a clear day you can see as far as 90 miles away. The Bascom Lodge is also located at the summit. Follow the Bellows Pipe hiking trail to Appalachian Trail and return along the same route. The best times to visit this trail are April through November. Dogs are welcome and may be off-leash in some areas.",
    length: 6.5,
    elevationGain: 2260,
    difficulty: "Hard",
    imageArray: "",
    hiked: false
},
{
    name: "Bash Bish Falls Trail",
    state: "Massachusetts",
    city: "Mount Washington,",
    description: "Bash Bish Falls is a great short hiking trail to the highest waterfall in the state of Massachusetts. You are soon rewarded with a view of the beautiful waterfall. The twin falls cascade into a serene pool. Swimming is not allowed in the pool. Use caution as the stones down around the falls are smooth and slick from years of traffic and it is easy to slip. The best times to visit this trail are April through November. Dogs are welcome, but must be on a leash.",
    length: 2.1,
    elevationGain: 521,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Treat Farm Trail",
    state: "Michigan",
    city: "Empire,",
    description: "Sleeping Bear Dunes National Lakeshore charges a fee to enter. The trail begins with a gravel road gradually sloping up to the 19th-century farmstead.  Following a look around the farm buildings, the trail continues across the former farm fields to the bluffs' edge overlooking the lake. There are trail options to continue along the bluff for a ways north, or you can retrace your steps and climb the steep Mount Baldy trail for panoramic 270-degree views of the south and west.",
    length: 23,
    elevationGain: 232,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Escarpment Trail",
    state: "Michigan",
    city: "Ontonagon,",
    description: "Beautiful views of the lake, many other hikers, red-eyed vireo near Government Peak. Not too buggy. A little technical near Government Peak. The best times to visit this trail are March through October. Dogs are welcome, but must be on a leash.",
    length: 8.4,
    elevationGain: 1666,
    difficulty: "Hard",
    imageArray: "",
    hiked: false
},
{
    name: "Upper & Lower Tahquamenon Falls",
    state: "Michigan",
    city: "Paradise,",
    description: "• Tahquamenon Falls State Park requires the Michigan Recreation Passport for vehicle entry. Both the Upper and Lower Falls have their own unique beauty. The Upper Falls drop more than 50 feet and are more than 200 feet wide, while the Lower Falls consist of five smaller falls that go around an island. The water has a unique amber, or 'root beer,'' color due to tannins from local trees  The best times to visit this trail are April through October. Dogs are welcome, but must be on a leash.",
    length: 10.2,
    elevationGain: 636,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Fifth Falls & Superior Hiking Trail Loop",
    state: "Minnesota",
    city: "Silver Creek Township,",
    description: "Every single fall is gorgeous and the state park team/rangers do a great job with the whole place. The best times to visit this trail are March through October. Dogs are welcome and may be off-leash in some areas.",
    length: 3.0,
    elevationGain: 298,
    difficulty: "Easy",
    imageArray: "",
    hiked: false
},
{
    name: "Silver Creek Trail",
    state: "Minnesota",
    city: "Carlton, ",
    description: "Beautiful trail! It’s worth going on the side trails down to the water. The trail is open year-round and is beautiful to visit anytime. Dogs are welcome, but must be on a leash.",
    length: 3.4,
    elevationGain: 291,
    difficulty: "Easy",
    imageArray: "",
    hiked: false
},
{
    name: "Baptism River",
    state: "Minnesota",
    city: "Silver Bay,",
    description: "Absolutely Beautiful. Hope you like stairs there is a lot of up and down. it's worth every step. The bridge at High Falls so go down the stairs to get a great view at the base of the falls. The best times to visit this trail are May through October. Dogs are welcome, but must be on a leash.",
    length: 2.9,
    elevationGain: 383,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Clark Creek Improved Trail",
    state: "Mississippi",
    city: "Woodville,",
    description: "An easy walk in and out, wide trails, well kept, easy access. Beautiful waterfalls! The trail is open year-round and is beautiful to visit anytime. Dogs are welcome, but must be on a leash.",
    length: 2.8,
    elevationGain: 429,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Red Bluff",
    state: "Mississippi",
    city: "Foxworth,",
    description: "Beautiful views and great moderate hike. Lots to stop and take in. Trails are not marked and a lot of it has washed out and been rerouted lately. A little steep and easy to lose your footing with all the roots. A lot of people get to the bottom(at the tracks) then follow the creek back into the base of the hill. Bring water shoes.",
    length: 0.9,
    elevationGain: 180,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Little Mountain Trail",
    state: "Mississippi",
    city: "Ackerman,",
    description: "This shady area is a great place to have a picnic and enjoy a short trip in nature. Grill some grub, have a picnic, then take a walk on the Little Mountain Trail. Its elevation is only 584 feet at the top, about 200 feet higher than the picnic area. Or you can drive there easily. The trail is open year-round and is beautiful to visit anytime. Dogs are welcome, but must be on a leash.",
    length: 1.8,
    elevationGain: 265,
    difficulty: "Easy",
    imageArray: "",
    hiked: false
},
{
    name: "Lewis & Clark Trail Trail Loop",
    state: "Missouri",
    city: "St. Charles,",
    description: "Nice hike, def on the easy side of moderate with some loose footing. Lots of shade. The views of the river are nice. Dogs are welcome, but must be on a leash.",
    length: 5.2,
    elevationGain: 564,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Mina Sauk Falls Trail",
    state: "Missouri",
    city: "Ironton,",
    description: "This a fairly easy hike, although the trail is rocky in some areas. The Mina Sauk Falls is at the half way point. This trail also intersects with the Ozark Trail. The trail is well marked. The trail is open year-round and is beautiful to visit anytime. Dogs are welcome, but must be on a leash.",
    length: 2.9,
    elevationGain: 433,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Lone Wolf Trail",
    state: "Missouri",
    city: "Ballwin,",
    description: "This trail parallels the River Scene Trail on top of the bluffs before plunging into the Kiefer Creek valley. The trail then follows the south bank of Kiefer Creek. There is also a creek crossing that connects this trail with Grotpeter Trail. The trail was originally built to allow bicyclists access to the bluff area, but it is also an excellent hiking trail. The trail is open year-round and is beautiful to visit anytime. Dogs are welcome, but must be on a leash.",
    length: 1.7,
    elevationGain: 223,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Avalanche Lake",
    state: "Montana",
    city: "Lake Mc Donald,",
    description: "Glacier National Park charges a fee to enter. The hike to Avalanche Lake is one of the most popular hikes in Glacier National Park due to the lake’s incredibly clear blue waters and the stunning views you will encounter throughout your trip. You can find the Avalanche Lake Trailhead not far from the West Entrance of the park just past Lake McDonald. The best times to visit this trail are June through October. You'll need to leave pups at home — dogs aren't allowed on this trail.",
    length: 5.9,
    elevationGain: 757,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Hidden Lake Trail",
    state: "Montana",
    city: "Siyeh Bend,",
    description: "Glacier National Park charges a fee to enter. Hidden Lake trail is both a challenging and rewarding hike from Logan Pass to a panoramic view of Hidden Lake! The trail begins from the west side of the Logan Pass Visitor Center. Starting at the back of the visitor center, veer right to the Hidden Lake Nature Trail Trailhead. The best times to visit this trail are June through October. You'll need to leave pups at home — dogs aren't allowed on this trail.",
    length: 5.3,
    elevationGain: 1374,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Lava Lake (Cascade Creek) Trail",
    state: "Montana",
    city: "Gallatin Gateway,",
    description: "The Lava Lake (Cascade Creek) climbs 1600 ft to a beautiful lake setting that is surrounded by the Spanish Peaks. The best times to visit this trail are June through October. Dogs are welcome and may be off-leash in some areas.",
    length: 6,
    elevationGain: 1620,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Redrock Falls via Swiftcurrent Pass",
    state: "Montana",
    city: "Siyeh Bend,",
    description: "Nice easy hike through the forest. Lakes are really pretty with nice reflections of mountains. Moose are known to visit these lakes. The best times to visit this trail are March through October. You'll need to leave pups at home — dogs aren't allowed on this trail.",
    length: 3.6,
    elevationGain: 236,
    difficulty: "Easy",
    imageArray: "",
    hiked: false
},
{
    name: "Walnut Creek Lake Trail West",
    state: "Nebraska",
    city: "Papillion,",
    description: "The Walnut Creek Lake Trail is three miles long, wide, has a concrete surface, and is nice and smooth! Signs advise hikers that it is about a one-hour walk. The trail has a few moderately steep hills in some areas. The trail is open year-round and is beautiful to visit anytime. Dogs are welcome, but must be on a leash.",
    length: 3.3,
    elevationGain: 160,
    difficulty: "Easy",
    imageArray: "",
    hiked: false
},
{
    name: "Antelope Creek Trail",
    state: "Nebraska",
    city: "Lincoln,",
    description: "Not a long hike but lots of wildlife including coyotes, bald eagles and fox. Plenty of rest spots. Not many bikes. Rock trail. Bathrooms in season. Dogs are welcome, but must be on a leash.",
    length: 2.3,
    elevationGain: 49,
    difficulty: "Easy",
    imageArray: "",
    hiked: false
},
{
    name: "North Overlook Trail",
    state: "Nebraska",
    city: "Gering,",
    description: "The North Overlook Trail is located at the end of the scenic park road at the summit of Scottsbluff National Monument. An easy paved loop leads to numerous scenic overlooks that take in the Platte River Valley, town of Scottsbluff, rugged badlands breaks along the south rim of the valley, and views as far away as Chimney Rock to the east. You'll need to leave pups at home — dogs aren't allowed on this trail.",
    length: 0.6,
    elevationGain: 39,
    difficulty: "Easy",
    imageArray: "",
    hiked: false
},
{
    name: "Calico Tanks Trail",
    state: "Nevada",
    city: "Las Vegas,",
    description: "Red Rock Canyon has put a reservation system in place for the Scenic Drive The best times to visit this trail are October through April. An amazing hike, lots of fun scrambling and beautiful rocks, it was so silent in the middle canyon. Dogs are welcome, but must be on a leash.",
    length: 2.2,
    elevationGain: 406,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Mary Jane Falls Trail",
    state: "Nevada",
    city: "Mount Charleston,",
    description: "One of the trails at Mt Charleston. Definitely a moderate hike uphill. The path is very visible. You can't get lost. Can be very slippery in places. A few areas with shade to stop and rest if needed. Weekends are busy, but it is well worth it to see the waterfall at the end. Great trail. The best times to visit this trail are April through December. Dogs are welcome, but must be on a leash.",
    length: 3.9,
    elevationGain: 1135,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Mokney Rock",
    state: "Nevada",
    city: "Village-Crystal Bay,",
    description: "Trail conditions were great—very well maintained. Even the off map short cut was extremely hikable. AllTrails map shows the longer trail. To take the short cut to Monkey Rock turn left when you see Chili’s watering hole. The views at the top are spectacular. Such a short hike for such great views. The best times to visit this trail are April through October. Dogs are welcome, but must be on a leash.",
    length: 2.6,
    elevationGain: 498,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Mount Rose Trail",
    state: "Nevada",
    city: "Incline Village-Crystal Bay,",
    description: "Absolutely beautiful trail. Gradual climb then levels off with beautiful scenery including high alpine meadows fed by waterfalls and creeks. Becomes slightly technical around the edge of a mountain then the gradual climbing begins. You’ll notice a sign a mile below the summit. It’s a good place to stop hydrate and rest a bit because it’s a long “gradual climb” mile but so worth it at the top. Panoramic beauty in all directions at the summit. Excellent trail! The best times to visit this trail are May through October. Dogs are welcome and may be off-leash in some areas.",
    length: 10.7,
    elevationGain: 2395,
    difficulty: "Hard",
    imageArray: "",
    hiked: false
},
{
    name: "",
    state: "New Hampshire",
    city: "",
    description: "",
    length: "",
    elevationGain: "",
    difficulty: "",
    imageArray: "",
    hiked: false
},
{
    name: "Mount Willard Trail",
    state: "New Hampshire",
    city: "Bretton Woods,",
    description: "Mount Willard Trail is a relatively steep day hike in the White Mountains that rewards with incredible views of Crawford Notch and the surrounding range. The best times to visit this trail are May through October. Dogs are welcome and may be off-leash in some areas.",
    length: 3.1,
    elevationGain: 895,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Welch-Dickey Loop Trail",
    state: "New Hampshire",
    city: "Thornton,",
    description: "The Welsh-Dickey is one the most popular hikes in White Mountain National Forest, and for good reason. The challenging route offers beautiful views of Waterville Valley, and the surrounding area. The best times to visit this trail are May through October. Dogs are welcome, but must be on a leash.",
    length: 4.4,
    elevationGain: 1778,
    difficulty: "Hard",
    imageArray: "",
    hiked: false
},
{
    name: "The Flume Gorge Trail",
    state: "New Hampshire",
    city: "Lincoln,",
    description: "Advanced Tickets and reservations via the website are required for this trail. The Flume Gorge trail is New Hampshire beauty, up close and personal.  Waterfalls, mosses, wild flowers, and trees line this beautiful boardwalk.  This is a relaxing must-see while hiking the more difficult trails around New Hampshire's White Mountains. The best times to visit this trail are May through October. You'll need to leave pups at home — dogs aren't allowed on this trail.",
    length: 2.2,
    elevationGain: 488,
    difficulty: "Easy",
    imageArray: "",
    hiked: false
},
{
    name: "Artist Bluff Trail",
    state: "New Hampshire",
    city: "Franconia,",
    description: "A nice, short 1.5 mile hike that's really worth it because the top view is absolutely beautiful. The best times to visit this trail are April through October. Dogs are welcome, but must be on a leash.",
    length: 1.5,
    elevationGain: 436,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Mount Tammany: Red Dot & Blue Dot Loop Trail",
    state: "New Jersey",
    city: "Pahaquarry,",
    description: "Mount Tammany is one of the most popular hikes in New Jersey, and for good reason! The trail offers sweeping views of the Delaware Water Gap, without too much of a challenge. The trailhead is also easily accessed, right off of Interstate 80 Dogs are welcome, but must be on a leash.",
    length: 3.6,
    elevationGain: 1243,
    difficulty: "Hard",
    imageArray: "",
    hiked: false
},
{
    name: "Vista Loop Trail",
    state: "New Jersey",
    city: "Mahwah,",
    description: "Hawk Rock Overlook (At the top of the initial ascent of the trail, a nice overlook view of the Ramapo Valley area including Ramapo College campus and on a clear day, the New York City skyline in the distance). The best times to visit this trail are April through November. Dogs are welcome, but must be on a leash.",
    length: 3.5,
    elevationGain: 636,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Long Loop via Peanut Leap Cascade, Giant Stairs & Closter Dock",
    state: "New Jersey",
    city: "Alpine,",
    description: "Trail is pretty tricky with a lot of Boulder scrambling along the water line. Multiple different terrains with a decent incline and decline. The best times to visit this trail are April through October. You'll need to leave pups at home — dogs aren't allowed on this trail.",
    length: 10.3,
    elevationGain: 1092,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Bearfort Ridge & Surprise lake Loop",
    state: "New Jersey",
    city: "West Milford,",
    description: "Really great hike with lots of views and a handful of technical rock scrambles. Definitely more difficult than anticipated but definitely doable for an average hiker. The best times to visit this trail are April through November. Dogs are welcome, but must be on a leash.",
    length: 8,
    elevationGain: 1400,
    difficulty: "Moderate",
    imageArray: "",
    hiked: false
},
{
    name: "Wheeler Peak via Williams Lake Trail",
    state: "New Mexico",
    city: "Taos Ski Valley,",
    description: "This is a very doable four-peak outing, with ample time for pictures, a long lunch, and wandering off trail. The atmosphere on this trail, especially at Wheeler Peak, was festive. The best times to visit this trail are June through October. Dogs are welcome and may be off-leash in some areas.",
    length: 8.5,
    elevationGain: 2972,
    difficulty: "Hard",
    imageArray: "",
    hiked: false
},
{
    name: "Nambe Lake Trail",
    state: "New Mexico",
    city: "Santa Fe,",
    description: "Beautiful hike! Last mile is hard but worth it when you get to the lake. Just keep taking breaks and have your all trails open parts where there is no trail. Bring a lunch and lots of water! Absolutely beautiful hike. The best times to visit this trail are May through October. Dogs are welcome and may be off-leash in some areas.",
    length: 6.7,
    elevationGain: 2080,
    difficulty: "Hard",
    imageArray: "",
    hiked: false
},
{
    name: "La Luz Trail #137",
    state: "New Mexico",
    city: "Placitas,",
    description: "There is a small fee to park. This trail at the north end of the Sandias goes from the base of the mountain to the peak at 10,678' and has beautiful views of the Albuquerque valley to the west. The best times to visit this trail are April through November. Dogs are welcome, but must be on a leash.",
    length: 12.3,
    elevationGain: 3572,
    difficulty: "Hard",
    imageArray: "",
    hiked: false
}

]