module.exports = [
{
    name: "Sougahoagdee Falls",
    state: "Alabama",
    city: "Houston,",
    description: "Huge rocks formation, lots of roots & rocks on the trail. The waterfall is at the end of the trail. Beware of leeches in the water & snakes along the way.",
    length: 4.0,
    elevationGain: 436,
    difficulty: "Easy",
    image: "",
    hiked: false
},
{
    name: "Little River Canyon",
    state: "Alabama",
    city: "Fort Payne,",
    description: "Heavy rock areas where good balance is needed. Great access to water & swimming. Handicap access to an overlook.",
    length: 1.4,
    elevationGain: 190,
    difficulty: "Easy",
    image: "",
    hiked: false
},
{
    name: "Cave Creek Trail from Cheaha Trailhead",
    state: "Alabama",
    city: "Lineville,",
    description: "Cave Creek has markings at trail junctions only. One very shallow water crossing. Some fallen trees to easily navigate around. The extra half mile to McDill Pointe is very worth the views.",
    length: 6.9,
    elevationGain: 1131,
    difficulty: "Moderate",
    image: "",
    hiked: false
},
{
    name: "Harding Icefield Trail",
    state: "Alaska",
    city: "Seward,",
    description: "Takes an average of 6 hours 29 min. Dogs are not allowed on this trail. Best times to visit: May - October. Pack layers, gets colder at the top.",
    length: 9.2,
    elevationGain: 3641,
    difficulty: "Hard",
    image: "",
    hiked: false
},
{
    name: "Portage Pass Trail",
    state: "Alaska",
    city: "Whittier,",
    description: "Stunning views of Portage Glacier & Lake. The traile is very rocky and a bit steep. Wear good shoes ground is usually wet.",
    length: 4.2,
    elevationGain: 1433,
    difficulty: "Moderate",
    image: "",
    hiked: false
},
{
    name: "Horseshoe Lake Trail",
    state: "Alaska",
    city: "Denali National Park,",
    description: "Fee to enter. Kids under 15 get in free. Stairs and hills, gets flat once you reach the lake. Make sure to look for the beaver dam.",
    length: 2.1,
    elevationGain: 393,
    difficulty: "Easy",
    image: "",
    hiked: false
},
{
    name: "Fossil Creek Falls",
    state: "Arizona",
    city: "Pine,",
    description: "Travel in a vehical suited for unpaved roads. A 1/4 mile walk from parking area to the waterfall trail then another mile to the waterfall. Enjoy a 25ft foot rock ledge that many people have jumped off of. Multiple swimming areas available. ",
    length: 2.42,
    elevationGain: 328,
    difficulty: "Moderate",
    image: "",
    hiked: false
},
{
    name: "Beaver Falls",
    state: "Arizona",
    city: "Supai,",
    description: "Enjoy incredible cascading pools over limestone terraces. Swim in the turquoise pools of Havasu Creek. It is recommended to start in the morning.",
    length: 5.2,
    elevationGain: 1200,
    difficulty: "Hard",
    image: "",
    hiked: false
},
{
    name: "Apache Falls",
    state: "Arizona",
    city: "Whiteriver,",
    description: "A $15 permit is required. The walk to the falls takes no more than 10 minutes. You will definitely hear the falls before you see them. The parking lot overlooks the rushing river and high canyon mountains. The rock formations surrounding the falls act as steps and lounge space; perfect for relaxing and enjoying yourself with a beautiful view.",
    length: 1,
    elevationGain: 100,
    difficulty: "Easy",
    image: "",
    hiked: false
},
{
    name: "",
    state: "Arkansas",
    city: "",
    description: "",
    length: 3,
    elevationGain: "",
    difficulty: "",
    image: "",
    hiked: false
},
{
    name: "",
    state: "",
    city: "",
    description: "",
    length: "",
    elevationGain: "",
    difficulty: "",
    image: "",
    hiked: false
},
{
    name: "",
    state: "",
    city: "",
    description: "",
    length: "",
    elevationGain: "",
    difficulty: "",
    image: "",
    hiked: false
},
{
    name: "",
    state: "",
    city: "",
    description: "",
    length: "",
    elevationGain: "",
    difficulty: "",
    image: "",
    hiked: false
},
{
    name: "",
    state: "",
    city: "",
    description: "",
    length: "",
    elevationGain: "",
    difficulty: "",
    image: "",
    hiked: false
},
{
    name: "",
    state: "",
    city: "",
    description: "",
    length: "",
    elevationGain: "",
    difficulty: "",
    image: "",
    hiked: false
},
{
    name: "",
    state: "",
    city: "",
    description: "",
    length: "",
    elevationGain: "",
    difficulty: "",
    image: "",
    hiked: false
},
{
    name: "",
    state: "",
    city: "",
    description: "",
    length: "",
    elevationGain: "",
    difficulty: "",
    image: "",
    hiked: false
},
]